### ISSUE TITLE
install dotnet

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#13]
using snap package to avoid having to add the GPG keys and repo.

however, the snap package has a bug

**Comment by VincentSaelzler** [comment]
specifying the channel of snap package seems possible, so can revert to a previous one to resolve issue.

```
tasks:
  - name: Install DotNetCore
    snap:
      name: dotnet-sdk 
      channel: 3.1
      classic: yes
      state: present
```

**Comment by VincentSaelzler** [comment]
here's a log of the problem:
https://github.com/dotnet/core/issues/4446

a workaround is to use the "edge" channel.

```
  - name: Install dotnet SDK.
    snap:
      classic: yes
      state: present
      name: dotnet-sdk
      channel: latest/edge
```
