### ISSUE TITLE
log requests to haproxy

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#168]

**Comment by VincentSaelzler** [comment]
followed tutorial:
https://www.haproxy.com/blog/introduction-to-haproxy-logging/

so far the setup kind of works, but not exactly as anticipated.

the logs all go to `var/log/haproxy.log` instead of being split between `/var/log/haproxy-traffic.log` and `/var/log/haproxy-admin.log`

i think it is because somehow a file got auto-created in `/etc/rsyslog.d`

- 49-haproxy.conf (auto gen - not sure why/how)
- haproxy-log.conf (i configured)

**Comment by VincentSaelzler** [comment]
no additional logging stuff required for now. the default contents of `49-haproxy.conf` are fine.
```
# Create an additional socket in haproxy's chroot in order to allow logging via
# /dev/log to chroot'ed HAProxy processes
$AddUnixListenSocket /var/lib/haproxy/dev/log

# Send HAProxy messages to a dedicated logfile
:programname, startswith, "haproxy" {
  /var/log/haproxy.log
  stop
}
```

**Comment by VincentSaelzler** [comment]
still leaves the task of deleting the extra files i made using the haproxy tutorial.

i will keep this ticket open and hold off on doing that until i can be sure that the base logging is good enough.

**Comment by VincentSaelzler** [comment]
take that back - without copying the additional file, the default contents of `49-haproxy.conf` do not show any of the traffic

**Comment by VincentSaelzler** [comment]
base logging config is basically good! just need to remove the stop command:

```
    - name: Modify the Default HAProxy Config (Defaults to ONLY Sending Logs to Local File)
      lineinfile:
        path: /etc/rsyslog.d/49-haproxy.conf
        line: '# stop # commenting so rsyslog will also send to other destinations'
        regexp: "^  stop$"
        state: present
```
