### ISSUE TITLE
get correct jinja version installed

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#180]
the rsyslog role is not running and it seems to be jinja version related.

**Comment by VincentSaelzler** [comment]
```
vince@devenv:~/src/hyper-homelab/ansible$ ansible --version
ansible [core 2.12.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vince/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/vince/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

**Comment by VincentSaelzler** [comment]
```
# Some Jinja2 filters are used that are available in the newer releases.
jinja2>=2.11.2
```
https://github.com/robertdebock/ansible-role-tomcat/blob/master/requirements.txt

**Comment by VincentSaelzler** [comment]
seems to be fixed by running this play as `vince`
```yml
  - name: Install python packages
    pip:
      name:
      - pexpect
      - proxmoxer
      - jinja2>=2.11.2 # required by robertdebock.rsyslog
```
