### ISSUE TITLE
change number of replicas to zero for new indices in elasticsearch

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#192]
we only currently have 1 node, so the status of elastic always shows as yellow

**Comment by VincentSaelzler** [comment]
```
PUT _component_template/singlenode
{
  "template": {
    "settings": {
      "number_of_replicas": 4
    }
  }
}
```

**Comment by VincentSaelzler** [comment]
able to create the component template, but seems like manually adding to index template is the best option for now

```
  - name: Login to an API
    uri:
      url: http://localhost:9200/_component_template/single-node
      method: PUT
      body_format: json
      body: '{ "template": { "settings": { "number_of_replicas": 0 } } }'
```
