### ISSUE TITLE
loop through calls to the provision-hyper-v role

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#33]
setting this on the back burner as-of 24ef1c549b50da069191f6dfaf5c9b9baa41a56a

here's the issue I am trying to solve:

playbook-local.yml
```
- name: Create a Hyper-V VM
  hosts: localhost
  become: no
  roles:
    - { role: "provision-hyper-v", vm_id: 28 }
    - { role: "provision-hyper-v", vm_id: 29 }
```

right now, the IDs of VMs need to manually be aligned with the inventory files

inventory.yml
```
all: 
  children: 
    virtual: 
      hosts:
        "192.168.1.28":
        "192.168.1.29":
```

also, the code which dictates where the VM artifacts (e.g. virtual hard disk files) are saved is buried within the role.

I think ideally, the code would drive off of an inventory file with related host_vars files.

There would need to be some sort of mechanism to lookup the vars for other hosts (since the only host that's running per ansible is localhost.)

at the very least, it would be better to loop through a list/dictionary variable that is kept in sync with the inventory file

**Comment by VincentSaelzler** [comment]
big breakthrough here: 03e8252e30ac0d9a7dcdbbb152e7d01b33200603

**Comment by VincentSaelzler** [comment]
as of a99a8a468fbba8f9ef4f1c5feedea23b4f341ebc have a relatively ok solution.

still not looping though

**Comment by VincentSaelzler** [comment]
https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html#information-about-ansible-magic-variables

looks like a good example:

```ruby
{% for host in groups['app_servers'] %}
   {{ hostvars[host]['ansible_facts']['eth0']['ipv4']['address'] }}
{% endfor %}
```

**Comment by VincentSaelzler** [comment]
this looks like it could be WAY BETTER!!
https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#delegating-tasks

**Comment by VincentSaelzler** [comment]
keys:
1. run playbook against the actual hosts we want VMs created for
1. utilize the `delegate_to` statement
1. save details related to the hyper_v host in a variable.

```yml
#provision.yml
- name: Create Hyper-V VMs if they don't already exist
  hosts: ubuntu_cloud #KEY 1
  gather_facts: no
  vars:
    - srv_det: "{{ hostvars['hyper_v'] }}" #KEY 2
  tasks:
  - name: Check if VHDX file exists
    delegate_to: hyper_v #KEY 3
```

with all this in place:
1. the looping is handled automatically by ansible (however many hosts are in the `ubuntu_cloud` group.)
1. the variables related to the individual hosts will be available for tasks (and roles using the `import_role` statement)
