### ISSUE TITLE
avoid assuming where provision-hyper-v role saves vhdx file

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#37]
playbook-local.yml
```yml
  tasks:
  - name: Check if dotnet VHDX file exists
    stat:
      # KLUDGE: assumes where the provision-hyper-v role saves the VHDX file
      path: "{{ vhd_dir }}{{ vms['dotnet']['id'] }}-os.vhdx" 
    register: dotnet_vhdx
```
