### ISSUE TITLE
connection refused error on reboot

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#38]
ubuntu-gui role
```yml
- name: Reboot system if required.
  command:
    cmd: shutdown -r now 'Rebooting to complete system upgrade'
    removes: /var/run/reboot-required
```
```
fatal: [192.168.1.27]: FAILED! => {"msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.27 port 22: Connection refused"}
```

**Comment by VincentSaelzler** [comment]
letting the machine reboot and running the playbook again works, but that's annoying

**Comment by VincentSaelzler** [comment]
looks like the correct way to do this is using ansible's built in `reboot` module

**Comment by VincentSaelzler** [comment]
the pattern of using the `command` module and then `removes: /var/run/reboot-required` was actually just a hack, which was causing the problem. this was not an upstream bug.

The **correct** way of doing things:

```yml
apt:
  [...]
register: apt_result
reboot:
when: apt_result['changed']
```
