### ISSUE TITLE
avoid duplicating and oddly splitting variable entry for virtualized hosts

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#49]
currently, some info about the virtual hosts lives in a dictionary variable called `vms` in `hostvars/hyper_v.yml`

```yml
vms:
  dotnet:
    id: 27
    name: dotnet
    vhd_size: 8589934592 # that's 8 GiB
    vcpus: 6
```

this should really all be stuff within `host_vars/dotnet`

when provisioning on the `hyper_v` host, will need to access the vars from the `dotnet` host like this: https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html#information-about-ansible-magic-variables

```j2
{{ hostvars['test.example.com']['ansible_facts']['distribution'] }}

```

this will likely be solved alongside #33

**Comment by VincentSaelzler** [comment]
keys:
1. run playbook against the actual hosts we want VMs created for
1. utilize the `delegate_to` statement
1. save details related to the hyper_v host in a variable.

```yml
#provision.yml
- name: Create Hyper-V VMs if they don't already exist
  hosts: ubuntu_cloud #KEY 1
  gather_facts: no
  vars:
    - srv_det: "{{ hostvars['hyper_v'] }}" #KEY 2
  tasks:
  - name: Check if VHDX file exists
    delegate_to: hyper_v #KEY 3
```

with all this in place:
1. the looping is handled automatically by ansible (however many hosts are in the `ubuntu_cloud` group.)
1. the variables related to the individual hosts will be available for tasks (and roles using the `import_role` statement)
