### ISSUE TITLE
recognize when bitcoin service is not running

### ISSUE THREAD

**Issue by VincentSaelzler** [VincentSaelzler/hyper-homelab#55]
possibly the auto-restart is what's making it not work?

```
systemctl status btc
● btc.service - Runs bitcoind.
     Loaded: loaded (/etc/systemd/system/btc.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2021-11-03 21:04:38 EDT; 4s ago
    Process: 13152 ExecStart=/home/vince/bitcoin/src/bitcoind (code=exited, status=203/EXEC)
   Main PID: 13152 (code=exited, status=203/EXEC)
```

I get an `ok` back from this task:
```yml
  - name: Start and enable bitcoin service
    systemd:
      name: btc
      state: started
      enabled: yes
```
